-- Corrections to the GOT 2022 catalogue imported by `0008_got_import.sql`.
--
-- Generated by scripts/extract-got.py from GOT_2022.pdf (the consolidated GOT,
-- gesetze-im-internet.de) against the catalogue as 0008 left it, and reviewed by hand.
-- Every change is guarded by the value it replaces, so an edit made through the
-- application since survives. Treatment lines keep their own copy of number, name and
-- fee, so nothing already billed changes.

-- Rows whose number had been read from their own description ("101 bis zu 150
-- Tieren"): they move to the position they describe, with that position's wording.
UPDATE service SET got_number = '46', name = 'Bestandsuntersuchung Kalb, 101 bis zu 150 Tieren'
 WHERE type = 'got' AND got_number = '101' AND name = 'Bestandsuntersuchung, Kalb, bis zu 150 Tieren';
UPDATE service SET got_number = '47', name = 'Bestandsuntersuchung Kalb, 151 bis zu 200 Tieren'
 WHERE type = 'got' AND got_number = '151' AND name = 'Bestandsuntersuchung Kalb, bis zu 200 Tieren';
UPDATE service SET got_number = '57', name = 'Bestandsuntersuchung Pelztier, Zucht- und Mastkaninchen, 201 bis zu 500 Tieren'
 WHERE type = 'got' AND got_number = '201' AND name = 'Bestandsuntersuchung, Pelztiere, Zuchtund Mastkaninchen, bis 500 Tiere';
UPDATE service SET got_number = '61', name = 'Bestandsuntersuchung Nutzgeflügel, 501 bis zu 1.000 Tieren'
 WHERE type = 'got' AND got_number = '501' AND name = 'Bestandsuntersuchung, Nutzgeflügel, bis 1.000 Tiere';
UPDATE service SET got_number = '63', name = 'Bestandsuntersuchung Nutzgeflügel, 2001 bis zu 3.000 Tieren'
 WHERE type = 'got' AND got_number = '2001' AND name = 'Bestandsuntersuchung, Nutzgeflügel, bis 3.000 Tiere';

-- Fees read from the wrong place.
UPDATE service SET net_price = 219.42
 WHERE type = 'got' AND got_number = '193' AND net_price = 23.51;

-- Suspended hyphens the extraction swallowed ("Zuchtund" → "Zucht- und").
UPDATE service SET name = 'Allgemeine Untersuchung mit Beratung, Pelztiere, Zucht- u. Mastkaninchen'
 WHERE type = 'got' AND got_number = '11' AND name = 'Allgemeine Untersuchung mit Beratung, Pelztiere, Zuchtu. Mastkaninchen';
UPDATE service SET name = 'Folgeuntersuchung im selben Behandlungsfall mit Beratung, Pelztiere, Zucht- u. Mastkaninchen'
 WHERE type = 'got' AND got_number = '29' AND name = 'Folgeuntersuchung im selben Behandlungsfall mit Beratung, Pelztiere, Zuchtu. Mastkaninchen';
UPDATE service SET name = 'Bestandsuntersuchung, Pelztiere, Zucht- und Mastkaninchen, bis zu 100 Tieren'
 WHERE type = 'got' AND got_number = '55' AND name = 'Bestandsuntersuchung, Pelztiere, Zuchtund Mastkaninchen, bis zu 100 Tieren';
UPDATE service SET name = 'Bestandsuntersuchung, Pelztiere, Zucht- und Mastkaninchen, ab 501 Tiere'
 WHERE type = 'got' AND got_number = '58' AND name = 'Bestandsuntersuchung, Pelztiere, Zuchtund Mastkaninchen, ab 501 Tiere';
UPDATE service SET name = 'Bestandsuntersuchung, Nutzgeflügel, Lege- und Zuchttiere, 5.001 bis 10.000 Tiere'
 WHERE type = 'got' AND got_number = '66' AND name = 'Bestandsuntersuchung, Nutzgeflügel, Legeund Zuchttiere, 5.001 bis 10.000 Tiere';
UPDATE service SET name = 'Bestandsuntersuchung, Nutzgeflügel, Lege- und Zuchttiere, 10.001 bis 15.000 Tiere'
 WHERE type = 'got' AND got_number = '67' AND name = 'Bestandsuntersuchung, Nutzgeflügel, Legeund Zuchttiere, 10.001 bis 15.000 Tiere';
UPDATE service SET name = 'Bestandsuntersuchung, Nutzgeflügel, Lege- und Zuchttiere, 15.001 bis 20.000 Tiere'
 WHERE type = 'got' AND got_number = '68' AND name = 'Bestandsuntersuchung, Nutzgeflügel, Legeund Zuchttiere, 15.001 bis 20.000 Tiere';
UPDATE service SET name = 'Bestandsuntersuchung, Nutzgeflügel, Lege- und Zuchttiere, 20.001 bis 50.000 Tiere'
 WHERE type = 'got' AND got_number = '69' AND name = 'Bestandsuntersuchung, Nutzgeflügel, Legeund Zuchttiere, 20.001 bis 50.000 Tiere';
UPDATE service SET name = 'Bestandsuntersuchung, Nutzgeflügel, Lege- und Zuchttiere, ab 50.001 Tiere'
 WHERE type = 'got' AND got_number = '70' AND name = 'Bestandsuntersuchung, Nutzgeflügel, Legeund Zuchttiere, ab 50.001 Tiere';
UPDATE service SET name = 'Bestandsgebühr, Rasse- und Ziertiere, die nicht der Erwerbstätigkeit ihrer Halter dienen'
 WHERE type = 'got' AND got_number = '86' AND name = 'Bestandsgebühr, Rasseund Ziertiere, die nicht der Erwerbstätigkeit ihrer Halter dienen';
UPDATE service SET name = 'Zerlegung, Pelztiere, Zucht- und Mastkaninchen'
 WHERE type = 'got' AND got_number = '112' AND name = 'Zerlegung, Pelztiere, Zuchtund Mastkaninchen';
UPDATE service SET name = 'Sektion mit pathologisch-anatomischer Diagnose einschließlich Bericht, Pelztiere, Zucht- und Mastkaninchen'
 WHERE type = 'got' AND got_number = '121' AND name = 'Sektion mit pathologisch-anatomischer Diagnose einschließlich Bericht, Pelztiere, Zuchtund Mastkaninchen';
UPDATE service SET name = 'Sektion mit pathologisch-anatomischen und histologischen Diagnosen einschließlich Bericht, Pelztiere, Zucht- und Mastkaninchen'
 WHERE type = 'got' AND got_number = '135' AND name = 'Sektion mit pathologisch-anatomischen und histologischen Diagnosen einschließlich Bericht, Pelztiere, Zuchtund Mastkaninchen';
UPDATE service SET name = 'Bestrahlungstherapie mittels Linearbeschleuniger (kuratives Protokoll, ohne Planungs- oder Kontroll-CT), pro Bestrahlung'
 WHERE type = 'got' AND got_number = '192' AND name = 'Bestrahlungstherapie mittels Linearbeschleuniger (kuratives Protokoll, ohne Planungsoder Kontroll-CT), pro Bestrahlung';
UPDATE service SET name = 'Bestrahlungstherapie mittels Linearbeschleuniger, (palliatives Protokoll, ohne Planungs- oder Kontroll-CT), pro Bestrahlung'
 WHERE type = 'got' AND got_number = '193' AND name = 'Bestrahlungstherapie mittels Linearbeschleuniger, (palliatives Protokoll, ohne Planungsoder Kontroll-CT), pro Bestrahlung';
UPDATE service SET name = 'Bestrahlungstherapie mittels Linearbeschleuniger (palliatives Protokoll bei Osteosarkom oder Arthrose, ohne Planungs- oder Kontroll-CT), pro Bestrahlung'
 WHERE type = 'got' AND got_number = '194' AND name = 'Bestrahlungstherapie mittels Linearbeschleuniger (palliatives Protokoll bei Osteosarkom oder Arthrose, ohne Planungsoder Kontroll-CT), pro Bestrahlung';
UPDATE service SET name = 'Euthanasie durch Injektion, Pelztiere, Zucht- u. Mastkaninchen'
 WHERE type = 'got' AND got_number = '204' AND name = 'Euthanasie durch Injektion, Pelztiere, Zuchtu. Mastkaninchen';
UPDATE service SET name = 'Instrumentelle Samenübertragung bei Einzeltieren, Pelztiere, Zucht- und Mastkaninchen'
 WHERE type = 'got' AND got_number = '532' AND name = 'Instrumentelle Samenübertragung bei Einzeltieren, Pelztiere, Zuchtund Mastkaninchen';
UPDATE service SET name = 'Blutuntersuchung: Leukozyten-, Erythrozyten-, Thrombozyten- oder Retikulozytenzählung, jeweils'
 WHERE type = 'got' AND got_number = '616' AND name = 'Blutuntersuchung: Leukozyten-, Erythrozyten-, Thrombozytenoder Retikulozytenzählung, jeweils';
UPDATE service SET name = 'Sehnen- und Muskelnaht'
 WHERE type = 'got' AND got_number = '894' AND name = 'Sehnenund Muskelnaht';
UPDATE service SET name = 'Sehnen- und Muskelnaht kompliziert'
 WHERE type = 'got' AND got_number = '895' AND name = 'Sehnenund Muskelnaht kompliziert';
UPDATE service SET name = 'Entfernung von Unterkiefer- oder Oberkieferteilen'
 WHERE type = 'got' AND got_number = '976' AND name = 'Entfernung von Unterkieferoder Oberkieferteilen';

-- The 75 positions the import missed: mostly fees of 333,34 € and
-- more, whose three-fold rate the old parser could not read, and the positions whose
-- numbers the misplaced rows above had taken.
INSERT INTO service (type, name, got_number, factor, vat_percent, net_price, hidden, draft)
VALUES
    ('got', 'Bestandsuntersuchung kleine Hauswiederkäuer, 151 bis zu 500 Tieren', '50', 100.000, 19.000, 50.38, false, false),
    ('got', 'Bestandsuntersuchung Pelztier, Zucht- und Mastkaninchen, 101 bis zu 200 Tieren', '56', 100.000, 19.000, 53.42, false, false),
    ('got', 'Bestandsuntersuchung Nutzgeflügel, 101 bis zu 500 Tieren', '60', 100.000, 19.000, 32.06, false, false),
    ('got', 'Anwesenheit bei Veranstaltungen, je Kalendertag (bis zu acht Stunden)', '76', 100.000, 19.000, 366.34, false, false),
    ('got', 'Punktion, Abszess, Zyste', '101', 100.000, 19.000, 15.39, false, false),
    ('got', 'Sektion mit pathologisch-anatomischen und histologischen Diagnosen einschließlich Bericht, Pferd, Hausequiden, Kameliden', '129', 100.000, 19.000, 365.70, false, false),
    ('got', 'Sektion mit pathologisch-anatomischen und histologischen Diagnosen einschließlich Bericht, Rind (adult)', '131', 100.000, 19.000, 365.70, false, false),
    ('got', 'Histologische/zytologische Untersuchung einer Probe (geringer Umfang bis zu zwei Lokalisationen/Organen)', '151', 100.000, 19.000, 34.13, false, false),
    ('got', 'CT-Untersuchung eines Körperteils', '175', 100.000, 19.000, 350.00, false, false),
    ('got', 'CT-Untersuchung von mehr als einem Körperteil, auch Ganzkörper-CT', '176', 100.000, 19.000, 500.00, false, false),
    ('got', 'Magnetresonanztomographie (MRT)', '177', 100.000, 19.000, 700.00, false, false),
    ('got', 'Szintigraphie Pferd', '179', 100.000, 19.000, 457.94, false, false),
    ('got', 'Euthanasie durch Injektion, Kalb', '201', 100.000, 19.000, 29.52, false, false),
    ('got', 'Operation eines abdominalen Kryptorchismus Hengst, Hausequiden, Kameliden', '384', 100.000, 19.000, 480.00, true, false),
    ('got', 'Operation einer Bauchwunde, perforierend, Pferd, Hausequiden, Kameliden', '426', 100.000, 19.000, 381.62, true, false),
    ('got', 'Laparotomie, diagnostisch, Pferd, Hausequiden, Kameliden', '459', 100.000, 19.000, 457.94, true, false),
    ('got', 'Operation am Ösophagus mit Thoraxöffnung', '465', 100.000, 19.000, 381.62, true, false),
    ('got', 'Enterotomie Pferd, Hausequiden, Kameliden', '479', 100.000, 19.000, 457.94, true, false),
    ('got', 'Darmresektion einschließlich Laparotomie, Pferd, Hausequiden, Kameliden (auch Kolik)', '481', 100.000, 19.000, 1350.00, true, false),
    ('got', 'Torsionsoperation Darm, Pferd, Hausequiden, Kameliden', '483', 100.000, 19.000, 534.25, true, false),
    ('got', 'Caecumresektion Pferd, Hausequiden, Kameliden (auch Kolik)', '485', 100.000, 19.000, 763.22, true, false),
    ('got', 'Inguinalhernie Ferkel', '501', 100.000, 19.000, 22.90, true, false),
    ('got', 'Gebärmuttervorfall, Reposition, kompliziert, Pferd, Hausequiden, Kameliden', '567', 100.000, 19.000, 419.78, false, false),
    ('got', 'Kaiserschnitt Stute', '586', 100.000, 19.000, 457.94, true, false),
    ('got', 'Fetotomie, mehr als drei Schnitte, Stute', '596', 100.000, 19.000, 365.70, true, false),
    ('got', 'Ovariohysterektomie Stute', '603', 100.000, 19.000, 534.25, true, false),
    ('got', 'Operation von Missbildungen am Herzen oder an den großen Gefäßen', '655', 100.000, 19.000, 381.62, true, false),
    ('got', 'Operation am offenen Herzen', '656', 100.000, 19.000, 572.43, true, false),
    ('got', 'Progressives Siebbeinhämatom, chirurgische Behandlung', '669', 100.000, 19.000, 548.55, true, false),
    ('got', 'Operative Entfernung eines gesamten vertikalen Gehörganges mit separater Eröffnung der Paukenhöhle', '680', 100.000, 19.000, 511.98, true, false),
    ('got', 'Brachycephalensyndrom, chirurgische Behandlung', '687', 100.000, 19.000, 487.60, true, false),
    ('got', 'Brachycephalensyndrom, chirurgische Behandlung, kompliziert', '688', 100.000, 19.000, 792.35, true, false),
    ('got', 'Larynxplastik', '689', 100.000, 19.000, 463.22, true, false),
    ('got', 'Kürzen des weichen Gaumens, Pferd, Hausequiden, Kameliden', '693', 100.000, 19.000, 341.32, true, false),
    ('got', 'Eröffnung des Kehlkopfes einschließlich Entfernung von Zubildungen und chirurgischer Behandlung von Verletzungen', '696', 100.000, 19.000, 335.07, true, false),
    ('got', 'Kehlkopfpfeifen, Operation, kompliziert', '698', 100.000, 19.000, 381.62, true, false),
    ('got', 'Kehlkopflähmung, Operation', '699', 100.000, 19.000, 463.22, true, false),
    ('got', 'Entfernung der Schilddrüse oder der Nebenschilddrüse, kompliziert', '701', 100.000, 19.000, 335.07, true, false),
    ('got', 'Kopperoperation', '702', 100.000, 19.000, 521.73, true, false),
    ('got', 'Milchleistenentfernung, vollständig', '715', 100.000, 19.000, 350.00, true, false),
    ('got', 'Resektion von Nervenscheidentumoren peripher', '725', 100.000, 19.000, 426.65, true, false),
    ('got', 'Resektion von Nervenscheidentumoren zentral', '726', 100.000, 19.000, 548.55, true, false),
    ('got', 'Kraniotomie', '729', 100.000, 19.000, 609.50, true, false),
    ('got', 'Ventral slot', '733', 100.000, 19.000, 548.55, true, false),
    ('got', 'Foraminotomie cervikal oder lumbosakral', '734', 100.000, 19.000, 609.50, true, false),
    ('got', 'Fenestration des Diskus intervertebralis, außer Halswirbelsäule', '735', 100.000, 19.000, 343.45, true, false),
    ('got', 'Serienfenestration des Diskus intervertebralis thorakolumbal', '737', 100.000, 19.000, 365.70, true, false),
    ('got', 'Spondylektomie, ventrale', '738', 100.000, 19.000, 457.94, true, false),
    ('got', 'Hemilaminektomie cervikal', '739', 100.000, 19.000, 548.55, true, false),
    ('got', 'Hemilaminektomie thorakolumbal', '740', 100.000, 19.000, 426.65, true, false),
    ('got', 'Laminektomie', '741', 100.000, 19.000, 487.60, true, false),
    ('got', 'Operation einer Wirbelfraktur', '742', 100.000, 19.000, 548.55, true, false),
    ('got', 'Korpektomie', '743', 100.000, 19.000, 548.55, true, false),
    ('got', 'Intraokulären Tumor entfernen', '821', 100.000, 19.000, 400.00, true, false),
    ('got', 'Grauer Star, chirurgische Behandlung', '825', 100.000, 19.000, 380.00, true, false),
    ('got', 'Glaskörperentfernung, kompliziert', '829', 100.000, 19.000, 341.32, true, false),
    ('got', 'Korrekturosteotomien an langen Röhrenknochen, kompliziert, je Seite', '860', 100.000, 19.000, 628.26, true, false),
    ('got', 'Tendovaginoskopie', '862', 100.000, 19.000, 365.70, true, false),
    ('got', 'Bursoskopie', '863', 100.000, 19.000, 426.65, true, false),
    ('got', 'Arthroskopische Operation einschließlich diagnostische Arthroskopie', '864', 100.000, 19.000, 463.22, true, false),
    ('got', 'Arthroskopische Operation einschließlich diagnostische Arthroskopie, kompliziert', '865', 100.000, 19.000, 548.55, true, false),
    ('got', 'Arthrotomische Operation ohne Fixation', '866', 100.000, 19.000, 381.62, true, false),
    ('got', 'Arthrotomische Operation mit Fixation', '867', 100.000, 19.000, 419.78, true, false),
    ('got', 'Arthrodese ohne Fixation', '868', 100.000, 19.000, 365.70, true, false),
    ('got', 'Arthrodese mit Fixation', '869', 100.000, 19.000, 853.30, true, false),
    ('got', 'Totalendoprothese', '879', 100.000, 19.000, 731.40, true, false),
    ('got', 'Kehlkopfpfeifen, Operation, kompliziert', '912', 100.000, 19.000, 463.22, true, false),
    ('got', 'Luftröhre, chirurgische Behandlung', '913', 100.000, 19.000, 381.62, true, false),
    ('got', 'Luftröhre, chirurgische Behandlung, kompliziert', '914', 100.000, 19.000, 534.25, true, false),
    ('got', 'Pneumothorax, chirurgische Behandlung, kompliziert', '918', 100.000, 19.000, 426.65, true, false),
    ('got', 'Thorakotomie', '919', 100.000, 19.000, 585.12, true, false),
    ('got', 'Entfernung von Unterkiefer- oder Oberkieferteilen kompliziert', '977', 100.000, 19.000, 365.70, true, false),
    ('got', 'Zystotomie einschließlich Laparotomie, Pferd, Hausequiden, Kameliden', '997', 100.000, 19.000, 800.00, true, false),
    ('got', 'Ureterabriss', '1001', 100.000, 19.000, 548.55, true, false),
    ('got', 'Partielle Blasenresektion und Augmentation kompliziert', '1003', 100.000, 19.000, 548.55, true, false);

-- Non-surgical positions the import hid: its chapter test matched "Nicht chirurgische
-- Behandlungen". Only where they are still hidden.
UPDATE service SET hidden = false
 WHERE type = 'got' AND hidden
   AND got_number IN ('362', '363', '364', '365', '366', '404', '405', '406', '417', '418', '419', '420', '421', '422', '423', '427', '428', '429', '430', '431', '432', '433', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '524', '525', '627', '628', '657', '658', '659', '660', '709', '716', '717', '718', '719', '720', '721', '722', '723', '724', '763', '764', '765', '766', '767', '768', '769', '770', '907', '921', '922', '984', '985', '986', '987', '988', '989', '990', '991', '992', '993', '994');

-- Surgical positions the import left visible. Only where they are still visible and
-- nothing uses them yet: a position already on a treatment line or in a template stays.
UPDATE service SET hidden = true
 WHERE type = 'got' AND NOT hidden
   AND got_number IN ('389', '390', '391', '392', '471', '472', '473', '474', '475', '476', '482', '484', '486', '487', '488', '492', '493', '494', '495', '496', '497', '498', '499', '500', '502', '593', '594', '595', '599', '600', '601', '602', '666', '670', '676', '677', '678', '679', '681', '682', '683', '684', '685', '690', '691', '692', '694', '695', '700', '730', '731', '732', '736', '775', '776', '780', '781', '782', '786', '787', '790', '791', '792', '793', '794', '795', '796', '797', '798', '799', '800', '801', '802', '803', '804', '805', '806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '822', '823', '824', '826', '827', '828', '830', '831', '832', '833', '846', '857', '858', '859', '861', '870', '871', '872', '873', '874', '875', '876', '877', '878', '951', '952', '953', '954', '955', '956', '957', '958', '959', '960', '961', '962', '963', '964', '965', '966', '967', '968', '969', '970', '971', '972', '973', '974', '975', '976')
   AND NOT EXISTS (SELECT 1 FROM treatment_item WHERE treatment_item.service_id = service.id)
   AND NOT EXISTS (SELECT 1 FROM treatment_template_item WHERE treatment_template_item.service_id = service.id);
